site_title: Nikl.me
email: hello@nikl.me
description: >- # this means to ignore newlines until "baseurl:"
  Personal homepage with a Blog, Pictures from traveling and
  a Portfolio with Java, HTML5, C++, and Python projects
keywords: "nikl, programming, hygames"
baseurl: ""
url: "https://jekyll.nikl.me"

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
syntax_highlighter: rouge

collections:
  posts:
    permalink: blog/:year/:title/
  destinations:
    output: true
    permalink: travelling/:year/:title/
  projects:
    output: true
    custom_permalink_placeholders: ["type"]
    permalink: projects/:type/:title/

defaults:
  -
    scope:
      path: ""
      type: "destinations"
    values:
      og_type: "article"
#      hide_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      og_type: "blog"
  -
    scope:
      path: ""
      type: "projects"
    values:
      og_type: "article"
#      hide_sidebar: true

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - Gemfile
  - Gemfile.lock

include:
  - _redirects