
site_title: Nikl.me
email: hello@nikl.me
description: >- # this means to ignore newlines until "baseurl:"
  Personal homepage with a Blog, Pictures from traveling and
  a Portfolio with Java, C++ and Python projects
baseurl: ""
url: "https://jekyll.nikl.me"
github_username:  NiklasEi

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
syntax_highlighter: rouge

collections:
  posts:
    permalink: blog/:year/:title/
  destinations:
    output: true
    hide_sidebar: true
    permalink: travelling/:year/:title/

exiftag:
  sources:
    - assets/images/destinations/2018/Poland

plugins:
  - jekyll-paginate-v2
  - jekyll-exiftag

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: 'Blog'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude:
  - .idea/
  - .gitignore
  - Gemfile
  - Gemfile.lock
# these are the files and directories that jekyll will exclude from the build
